image: maven:3.6.3-jdk-8

stages:
  - build
  - test
  - package
  - deploy

attempt-build:
  stage: build
  script:
      - mvn clean compile | tee compileStepOutput.txt
      - cat compileStepOutput.txt | grep -i warning| tee compilerWarnings.txt
      - if [ $(cat compileStepOutput.txt | grep -i warning | wc -l) -gt 4 ]; then echo -e "\033[0;31m[ERROR]\033[0m Too many compiler warnings!"; false; fi
  artifacts:
    expire_in: never
    paths:
      - compilerWarnings.txt

coverage-test:
  stage: test
  script:
    - mvn test
    - mvn jacoco:report
    - "awk -F \",\" '{ instructions += $4 + $5; covered += $5 } END { print covered, \"/\", instructions, \"instructions covered\"; print \"Instructions covered: \"100*covered/instructions, \"%\" }' target/site/jacoco/jacoco.csv"
  coverage: "/Instructions covered:\\s\\d+\\.*\\d*\\s%/"
  artifacts:
<<<<<<< HEAD
    paths:
      - target/jacoco.exec
      - target/site/jacoco/
=======
    expire_in: never
    paths:
      - target/jacoco.exec
      - target/site/jacoco/
      - target/surefire-reports/
>>>>>>> master
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

package-client:
  stage: package
<<<<<<< HEAD
  script: mvn clean package
  only:
    - merge_requests

deploy-client:
  stage: deploy
  script: mvn clean deploy
  only:
    - merge_requests
=======
  script:
    - mvn clean package | tee packageStepOutput.txt
    - cat packageStepOutput.txt | grep -i warning| tee packageWarnings.txt
    - if [ $(cat packageStepOutput.txt | grep -i warning | wc -l) -gt 4 ]; then echo -e "\033[0;31m[ERROR]\033[0m Too many packaging warnings!"; false; fi
  artifacts:
    expire_in: never
    paths:
      - packageWarnings.txt
      - target/minecraft.plugin.squidsquad-1.0-SNAPSHOT.jar

#deploy-client:
#  stage: deploy
#  script: mvn clean deploy
#  only:
#    - merge_requests
>>>>>>> master
